version: '3.3'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  fluentd:
    image: custom-fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - 'elasticsearch'
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    networks:
      - elk

        #  logstash:
        #    build:
        #      context: logstash/
        #      args:
        #        ELK_VERSION: $ELK_VERSION
        #    volumes:
        #      - type: bind
        #        source: ./logstash/config/logstash.yml
        #        target: /usr/share/logstash/config/logstash.yml
        #        read_only: true
        #      - type: bind
        #        source: ./logstash/pipeline
        #        target: /usr/share/logstash/pipeline
        #        read_only: true
        #    ports:
        #      - "5000:5000/tcp"
        #      - "5000:5000/udp"
        #      - "9600:9600"
        #    environment:
        #      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
        #    networks:
        #      - elk
        #    depends_on:
        #      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      - TZ=Asia/Taipei
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
